version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: neos_core_db
    environment:
      POSTGRES_USER: neos_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: neos_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: